#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Prism >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Prism=/luci-static/prism
		set luci.main.mediaurlbase=/luci-static/prism
		commit luci
	EOF
fi

exit 0
